import Navbar from "@/components/Navbar"
import { ThemeProvider } from "@/components/Template/theme-provider"
import { Fira_Code } from "next/font/google"
import "./styles/globals.css"
import "animate.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
}
const fira = Fira_Code({ subsets: ["latin"] })

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-[#FCFCFC] dark:bg-[#1c1c1c] text-black dark:text-white ${fira.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="py-10">
            <Navbar />
            <main className="px-2.5 mt-10">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
